// Tag colors map to CSS variables
const TAG_COLORS = {
  openai: 'openai', anthropic: 'anthropic', google: 'google',
  meta: 'meta', microsoft: 'microsoft', nvidia: 'nvidia',
  xai: 'xai', deepseek: 'deepseek', research: 'research',
  infrastructure: 'infra', drama: 'drama', funding: 'funding',
  apple: 'apple'
};

const FILTER_CHIPS = [
  { id: 'all', label: 'All', color: null },
  { id: 'openai', label: 'OpenAI', color: 'openai' },
  { id: 'anthropic', label: 'Anthropic', color: 'anthropic' },
  { id: 'google', label: 'Google / DeepMind', color: 'google' },
  { id: 'meta', label: 'Meta', color: 'meta' },
  { id: 'microsoft', label: 'Microsoft', color: 'microsoft' },
  { id: 'xai', label: 'xAI', color: 'xai' },
  { id: 'deepseek', label: 'DeepSeek / China', color: 'deepseek' },
  { id: 'nvidia', label: 'NVIDIA', color: 'nvidia' },
  { id: 'research', label: 'Research', color: 'research' },
  { id: 'infrastructure', label: 'Infrastructure', color: 'infra' },
  { id: 'drama', label: 'Drama', color: 'drama' },
  { id: 'funding', label: 'Funding', color: 'funding' },
];

const ERAS = [
  {
    id: 'foundations',
    number: 1,
    title: 'Foundations',
    range: '1950 – 2011',
    blurb: 'The decades where AI was mostly a dream and a research curiosity.',
    events: [
      { date: '1950', title: 'The Turing Test', actor: 'Alan Turing', accent: 'research', tags: ['research'],
        why: 'Sets the bar for what AI is even trying to do.',
        body: 'Turing publishes "Computing Machinery and Intelligence," proposing the "imitation game": if a machine can convince a human it\'s human via text alone, that counts as intelligence. This thought experiment shaped the entire conversation about machine intelligence for the next 70+ years.' },
      { date: '1956', title: 'Dartmouth Workshop', actor: 'McCarthy, Minsky, Shannon, Rochester', accent: 'research', tags: ['research'],
        why: 'AI officially becomes a field.',
        body: 'A summer research project at Dartmouth College where the term "artificial intelligence" was coined. The first dedicated AI conference and the moment AI became a recognized scientific discipline.' },
      { date: '1958', title: 'The Perceptron', actor: 'Frank Rosenblatt', accent: 'research', tags: ['research'],
        why: 'The seed of every modern AI model.',
        body: 'The Mark I Perceptron — a trainable neural network that could learn to classify simple images. The first machine that improved its own performance through learning, not just rules.' },
      { date: '1974–87', title: 'The AI Winters', actor: 'The whole field', accent: 'research', tags: ['research'],
        why: 'A reminder that AI progress isn\'t linear.',
        body: 'Funding and interest in AI collapsed twice when promises outran reality and hardware lagged. Nearly killed the field before it recovered. The lesson: AI cycles are dramatic.' },
      { date: '1997', title: 'Deep Blue beats Kasparov', actor: 'IBM', accent: 'research', tags: ['research'],
        why: 'First time a machine clearly out-thought humans at a "thinking" task.',
        body: 'IBM\'s chess computer defeated world champion Garry Kasparov 3.5–2.5 in a six-game rematch in New York. Brute-force search, not learning — but a public moment that proved machines could exceed humans at strategic reasoning.' },
      { date: '2011', title: 'Watson wins Jeopardy!', actor: 'IBM', accent: 'research', tags: ['research'],
        why: 'Showed AI could handle messy human language, not just rules.',
        body: 'IBM\'s Watson defeated champions Brad Rutter and Ken Jennings on Jeopardy!. Demonstrated that AI could master language understanding, wordplay, and open-domain knowledge retrieval — not just formal puzzle-solving.' },
    ]
  },
  {
    id: 'deep-learning',
    number: 2,
    title: 'The Deep Learning Revolution',
    range: '2012 – 2017',
    blurb: 'Neural networks suddenly start working — because GPUs got fast enough.',
    events: [
      { date: '2012', title: 'AlexNet & ImageNet', actor: 'Krizhevsky, Sutskever, Hinton', accent: 'research', tags: ['research'],
        why: 'Triggered the modern deep learning boom.',
        body: 'AlexNet won ImageNet with a 15.3% top-5 error rate vs. 26% for second place — a stunning leap. Proved deep neural networks on GPUs could crush traditional computer vision. Ilya Sutskever, one of the authors, would later co-found OpenAI.' },
      { date: '2013', title: 'Word2Vec', actor: 'Tomáš Mikolov, Google', accent: 'google', tags: ['google', 'research'],
        why: 'Proof that language has math hiding inside it.',
        body: 'A simple neural network trained on text could solve "king − man + woman = queen" through vector arithmetic. Demonstrated that machines could discover linguistic structure on their own.' },
      { date: '2014', title: 'GANs', actor: 'Ian Goodfellow', accent: 'research', tags: ['research'],
        why: 'Birth of AI-generated images, deepfakes, and creative AI.',
        body: 'Generative Adversarial Networks: two neural networks compete — one generating fakes, one detecting them. Unlocked a decade of synthetic media generation.' },
      { date: '2014', title: 'Google buys DeepMind', actor: 'Google', accent: 'google', tags: ['google', 'funding'],
        why: 'DeepMind becomes Google\'s elite AI lab.',
        body: 'Google acquires the London-based AI startup founded by Demis Hassabis, Shane Legg, and Mustafa Suleyman for ~$500M. DeepMind would go on to build AlphaGo, AlphaFold, and (eventually) Gemini.' },
      { date: 'Mar 2016', title: 'AlphaGo beats Lee Sedol', actor: 'DeepMind', accent: 'google', tags: ['google', 'research'],
        why: 'Cracked a game everyone thought was 10 years out.',
        body: 'Defeated 18-time world Go champion Lee Sedol 4–1 in Seoul, watched by 200M+ people. Go was considered too intuitive and creative for machines. The moment AI felt suddenly real to a global audience.' },
      { date: 'Jun 2017', title: '"Attention Is All You Need"', actor: 'Vaswani et al., Google', accent: 'google', tags: ['google', 'research'],
        why: 'The single most important paper in modern AI.',
        body: 'Eight Google researchers publish the Transformer architecture — replacing recurrent networks with attention. Every modern chatbot, including ChatGPT and Claude, descends from this paper. Quietly released, world-changing.' },
    ]
  },
  {
    id: 'llm-era',
    number: 3,
    title: 'The Transformer & LLM Era',
    range: '2018 – 2022',
    blurb: 'Transformer + huge data + huge GPUs = something nobody quite expected.',
    events: [
      { date: 'Jun 2018', title: 'GPT-1', actor: 'OpenAI', accent: 'openai', tags: ['openai'],
        why: 'First "Generative Pre-trained Transformer" — proof of concept.',
        body: '117 million parameters. Showed that pre-training on huge text corpora then fine-tuning could beat task-specific models. The G, P, and T of GPT all start here.' },
      { date: 'Oct 2018', title: 'BERT', actor: 'Google', accent: 'google', tags: ['google'],
        why: 'Made language understanding mainstream — and powered Google Search.',
        body: 'Bidirectional Encoder Representations from Transformers. Set new records on 11 NLP benchmarks and was deployed inside Google Search to handle billions of queries.' },
      { date: 'Feb 2019', title: 'GPT-2', actor: 'OpenAI', accent: 'openai', tags: ['openai'],
        why: 'First model that wrote scarily coherent text.',
        body: '1.5 billion parameters. OpenAI initially delayed full release citing misuse concerns — the first time an AI lab said "this might be too dangerous to release as-is."' },
      { date: '2019', title: 'OpenAI restructures + Microsoft $1B', actor: 'OpenAI / Microsoft', accent: 'microsoft', tags: ['openai', 'microsoft', 'funding'],
        why: 'The deal that funded the next 5 years of frontier AI.',
        body: 'OpenAI created OpenAI LP, a "capped-profit" subsidiary controlled by the original nonprofit, to allow venture funding while limiting investor returns. Microsoft invested $1B and became the exclusive cloud provider on Azure. The partnership eventually grew past $13B.' },
      { date: 'May 2020', title: 'GPT-3', actor: 'OpenAI', accent: 'openai', tags: ['openai'],
        why: 'First model where you could just ask for things and it figured out what you meant.',
        body: '175 billion parameters, trained on 570GB of text. Demonstrated "few-shot learning" — solving new tasks from a handful of examples in the prompt. The moment serious people started saying "AGI might be possible."' },
      { date: 'Jul 2020', title: 'AlphaFold 2', actor: 'DeepMind', accent: 'google', tags: ['google', 'research'],
        why: 'First time AI made a serious scientific discovery.',
        body: 'Solved the 50-year-old protein folding problem at the CASP14 contest with 92.4% accuracy on hard proteins. Within years, AlphaFold predicted the structures of 200+ million proteins — every known protein.' },
      { date: 'Jun 2021', title: 'GitHub Copilot', actor: 'OpenAI / GitHub', accent: 'openai', tags: ['openai', 'microsoft'],
        why: 'AI starts writing real code professionally.',
        body: 'Powered by OpenAI\'s Codex model (a GPT-3 variant fine-tuned on code). The first widely-used AI pair-programmer. Made it suddenly obvious AI had real economic value.' },
      { date: 'Apr 2022', title: 'DALL-E 2', actor: 'OpenAI', accent: 'openai', tags: ['openai'],
        why: 'AI image generation goes mainstream.',
        body: 'Photorealistic images from text prompts. The first image-gen model to go viral with the general public. Sparked enormous interest in generative AI just before ChatGPT.' },
      { date: 'Aug 2022', title: 'Stable Diffusion (open-source)', actor: 'Stability AI', accent: 'research', tags: ['research'],
        why: 'Image AI escapes the labs — anyone can run it on a laptop.',
        body: 'Released for free with weights downloadable. Unleashed a wave of open-source AI tooling and art. Set the template for "open models" that would later define LLaMA and DeepSeek.' },
    ]
  },
  {
    id: 'chatgpt',
    number: 4,
    title: 'The ChatGPT Earthquake',
    range: 'Late 2022 – 2023',
    blurb: 'The moment AI stopped being for researchers and became a household word.',
    events: [
      { date: 'Nov 30, 2022', title: 'ChatGPT launches', actor: 'OpenAI', accent: 'openai', tags: ['openai'],
        why: 'Fastest-growing consumer product in history. The starting gun.',
        body: 'A free, conversational interface on top of GPT-3.5. 1 million users in 5 days. 100 million in 2 months. Triggered the modern AI gold rush and forced every major tech company to ship an AI product.' },
      { date: 'Feb 2023', title: 'Meta\'s LLaMA leaks', actor: 'Meta', accent: 'meta', tags: ['meta'],
        why: 'Accidentally launched the open-source AI movement.',
        body: 'Meta released LLaMA to researchers. Within days the weights leaked onto 4chan and BitTorrent. The leak supercharged independent AI development outside the big labs.' },
      { date: 'Mar 14, 2023', title: 'GPT-4', actor: 'OpenAI', accent: 'openai', tags: ['openai'],
        why: 'The new ceiling for AI capability.',
        body: 'Multimodal (text + images), passed the bar exam in the 90th percentile. Set the standard the entire industry would chase for 18+ months.' },
      { date: 'Mar 2023', title: 'Claude 1', actor: 'Anthropic', accent: 'anthropic', tags: ['anthropic'],
        why: 'Anthropic\'s first public model. The OpenAI rival is real.',
        body: 'Released to select users. Demonstrated Anthropic\'s "Constitutional AI" approach — training models against a written set of principles rather than purely human feedback.' },
      { date: 'Jul 2023', title: 'xAI founded', actor: 'Elon Musk', accent: 'xai', tags: ['xai'],
        why: 'Musk is back in the AI race after leaving OpenAI in 2018.',
        body: 'Musk announces xAI with a team poached from DeepMind, Google, Microsoft, and Tesla. Mission: "understand the true nature of the universe." Practical mission: not let OpenAI win.' },
      { date: 'Jul 2023', title: 'LLaMA 2 released open-source', actor: 'Meta', accent: 'meta', tags: ['meta'],
        why: 'Frontier AI is no longer locked up.',
        body: 'Meta releases LLaMA 2 with a permissive license allowing commercial use. The first time a major lab seriously committed to open weights. Mark Zuckerberg becomes the unlikely hero of open-source AI.' },
      { date: 'Dec 2023', title: 'Google merges Brain + DeepMind', actor: 'Google', accent: 'google', tags: ['google'],
        why: 'Google realized it was losing the race and consolidated.',
        body: 'Two of Google\'s separate AI groups merge into "Google DeepMind" under Demis Hassabis. A clear admission that Google\'s Bard launch had stumbled and the company needed to focus.' },
    ]
  },
  {
    id: 'two-horse',
    number: 5,
    title: 'Two-Horse Race: OpenAI vs. Anthropic',
    range: '2020 – present',
    blurb: 'Two labs, founded by people who used to work together, now define the frontier.',
    events: [
      { date: 'Dec 2015', title: 'OpenAI founded as a nonprofit', actor: 'Altman, Musk, Brockman, Sutskever +', accent: 'openai', tags: ['openai', 'funding'],
        why: 'Established the field\'s first major safety-focused AI lab.',
        body: 'Sam Altman, Elon Musk, Greg Brockman, Ilya Sutskever, and six others founded OpenAI as a nonprofit research lab with $1B promised funding. Mission: build safe AGI that benefits all of humanity.' },
      { date: 'Feb 2018', title: 'Elon Musk leaves OpenAI board', actor: 'Elon Musk', accent: 'drama', tags: ['openai', 'drama'],
        why: 'A foundational rift that would resurface years later in court.',
        body: 'Musk resigns citing "conflict of interest" with Tesla\'s AI work. Reality: he wanted majority equity and CEO control; OpenAI refused. His promised $1B donations stopped after just $100M.' },
      { date: 'Late 2020', title: 'The Amodeis leave to start Anthropic', actor: 'Dario & Daniela Amodei + 7 others', accent: 'anthropic', tags: ['anthropic', 'drama'],
        why: 'Created the first major OpenAI competitor — built around safety.',
        body: 'Dario Amodei (OpenAI VP of Research), his sister Daniela, and seven senior researchers leave over disagreements about pace and safety. They believe OpenAI is moving too fast.' },
      { date: 'Sep 2021', title: 'Anthropic publicly founded', actor: 'Anthropic', accent: 'anthropic', tags: ['anthropic'],
        why: 'A safety-first AI lab built from OpenAI defectors.',
        body: 'Anthropic publicly launches with a mission to build safe, steerable AI. Develops Constitutional AI and pioneers mechanistic interpretability — literally looking inside models to see what they\'re "thinking."' },
      { date: 'Jul 2023', title: 'Claude 2', actor: 'Anthropic', accent: 'anthropic', tags: ['anthropic'],
        why: 'Anthropic goes public to consumers.',
        body: 'First Claude model available to the general public. 100K-token context window — far ahead of GPT-4 at the time.' },
      { date: 'Nov 6, 2023', title: 'GPT-4 Turbo + 128K context', actor: 'OpenAI', accent: 'openai', tags: ['openai'],
        why: 'Bigger memory, lower price.',
        body: '16x larger context than original GPT-4 (8K → 128K). Cheaper API pricing. Made GPT-4-class capability accessible to far more developers.' },
      { date: 'Nov 17, 2023', title: 'Sam Altman fired by OpenAI board', actor: 'OpenAI board', accent: 'drama', tags: ['openai', 'drama'],
        why: 'The closest thing AI has had to a corporate coup.',
        body: 'The board removes Altman citing "lack of candor in his communications." Within hours Greg Brockman quits in solidarity. Investors and employees panic.' },
      { date: 'Nov 20, 2023', title: 'Altman rehired after employee revolt', actor: 'OpenAI', accent: 'drama', tags: ['openai', 'drama'],
        why: 'The board lost a 72-hour standoff against the staff.',
        body: '~700 of OpenAI\'s ~770 employees signed a letter threatening to follow Altman to Microsoft. Altman returned with a restructured board (Bret Taylor, Larry Summers, Adam D\'Angelo).' },
      { date: 'Nov 2023', title: 'Claude 2.1 — 200K context', actor: 'Anthropic', accent: 'anthropic', tags: ['anthropic'],
        why: 'Doubled context to ~500 pages of text in a single conversation.',
        body: 'Now the longest context window of any frontier model. Enabled large document analysis use-cases that weren\'t possible before.' },
      { date: 'Mar 2024', title: 'Claude 3 family — Haiku, Sonnet, Opus', actor: 'Anthropic', accent: 'anthropic', tags: ['anthropic'],
        why: 'Anthropic\'s tiered approach: fast/cheap, balanced, flagship.',
        body: 'Three models at different price/capability points. Native vision support. The "Opus → Sonnet → Haiku" naming convention sticks for years.' },
      { date: 'May 13, 2024', title: 'GPT-4o', actor: 'OpenAI', accent: 'openai', tags: ['openai'],
        why: 'Truly multimodal: text + image + audio + video, in real time.',
        body: 'Responds to audio in ~320ms — human conversation speed. Unified all modalities into one native architecture, dramatically reduced API costs.' },
      { date: 'May 2024', title: 'Sutskever & Leike leave OpenAI', actor: 'Ilya Sutskever, Jan Leike', accent: 'drama', tags: ['openai', 'anthropic', 'drama'],
        why: 'OpenAI loses its co-founder/chief scientist and head of alignment.',
        body: 'Sutskever founds Safe Superintelligence Inc. (SSI). Leike (head of alignment) joins Anthropic, publicly stating "safety culture and processes have taken a backseat to shiny products."' },
      { date: 'Jun 2024', title: 'Claude 3.5 Sonnet', actor: 'Anthropic', accent: 'anthropic', tags: ['anthropic'],
        why: 'A mid-tier model that beat the previous flagship — and GPT-4o.',
        body: 'Outperformed Claude 3 Opus on most benchmarks while being faster and cheaper. Solved 64% of complex coding problems on real-world benchmarks. The point Anthropic became developer-favorite.' },
      { date: 'Sep 12, 2024', title: 'o1 — first "thinking" reasoning model', actor: 'OpenAI', accent: 'openai', tags: ['openai'],
        why: 'Fundamental shift: trade compute-at-runtime for accuracy.',
        body: 'A model that "thinks" internally before answering, using reinforcement learning to solve math, code, and science at PhD level. Unlocked problems brute-force scaling couldn\'t.' },
      { date: 'Oct 2024', title: 'Computer Use + Claude 3.5 Haiku', actor: 'Anthropic', accent: 'anthropic', tags: ['anthropic'],
        why: 'First frontier model that could control a computer like a person.',
        body: 'Claude can see screens, move cursors, click buttons, and complete real desktop tasks. The opening shot of the "agentic AI" era.' },
      { date: 'Oct 2024', title: '$6.6B funding round, $157B valuation', actor: 'OpenAI', accent: 'funding', tags: ['openai', 'funding'],
        why: 'One of the largest private fundraises ever — at the time.',
        body: 'Microsoft, Nvidia, and SoftBank lead. Funded the next phase of compute. Would soon be eclipsed by even bigger rounds.' },
      { date: 'Nov 2024', title: 'Model Context Protocol (MCP) released', actor: 'Anthropic', accent: 'anthropic', tags: ['anthropic', 'infrastructure'],
        why: 'Becomes the industry standard for connecting AI to tools.',
        body: 'Open-sourced spec for plugging AI models into external data sources and tools. Adopted across the industry within months. Solved the "every integration needs custom glue" problem.' },
      { date: 'Dec 2024', title: 'o3 announced', actor: 'OpenAI', accent: 'openai', tags: ['openai'],
        why: 'Massive reasoning leap in just months.',
        body: 'Scored 96.7% on AIME (vs. o1\'s 83%) and 87.7% on graduate-level science. Showed the o-series reasoning approach was scaling fast.' },
      { date: 'Dec 2024', title: 'Sora — public release', actor: 'OpenAI', accent: 'openai', tags: ['openai'],
        why: 'Generative AI extends to video.',
        body: 'Text-to-video generation rolled out to ChatGPT Plus/Pro users. Quality and policy limits remained, but the genie was out.' },
      { date: 'Jan 2025', title: 'Anthropic at $60B valuation + Google adds $1B', actor: 'Anthropic', accent: 'funding', tags: ['anthropic', 'funding', 'google'],
        why: 'Anthropic now firmly in the elite tier.',
        body: 'Google commits another $1B alongside Anthropic\'s $60B valuation. Two cloud giants — Amazon and Google — both heavily invested.' },
      { date: 'Feb 2025', title: 'Claude 3.7 Sonnet + Claude Code', actor: 'Anthropic', accent: 'anthropic', tags: ['anthropic'],
        why: 'Extended thinking + a serious coding agent.',
        body: 'Introduced "extended thinking" — Claude\'s version of o-style reasoning. Output capacity expanded to 128K tokens. Claude Code ships as a terminal-based agentic coding tool.' },
      { date: 'May 2025', title: 'Claude 4 family — Sonnet 4 & Opus 4', actor: 'Anthropic', accent: 'anthropic', tags: ['anthropic'],
        why: 'Anthropic\'s next-gen flagships.',
        body: 'Sonnet 4 (balanced workhorse) and Opus 4 (reasoning flagship). Released alongside Amazon\'s investment reaching $8B total.' },
      { date: 'Aug 7, 2025', title: 'GPT-5', actor: 'OpenAI', accent: 'openai', tags: ['openai'],
        why: 'OpenAI\'s next major leap.',
        body: 'Significant improvements in math, programming, finance, and multimodal. Faster responses, less hallucination. Continued scaling pays off after the o-series reasoning breakthroughs.' },
      { date: 'Sep–Nov 2025', title: 'Claude 4.5 family', actor: 'Anthropic', accent: 'anthropic', tags: ['anthropic'],
        why: 'Opus 4.5 — first model to break 80% on SWE-bench.',
        body: 'Sonnet 4.5 (Sept 29) and Opus 4.5 (Nov 24). Hybrid reasoning, 200K context, 64K output. Opus 4.5 hit 80.9% on SWE-bench while cutting costs by 67%.' },
      { date: 'Mar 2025', title: '$40B SoftBank-led round, $300B valuation', actor: 'OpenAI', accent: 'funding', tags: ['openai', 'funding'],
        why: 'Largest private funding round ever, at the time.',
        body: 'SoftBank leads with $30B. Reflects OpenAI\'s dominance in enterprise AI market share and the staggering capital frontier AI now demands.' },
      { date: 'Feb 2026', title: 'Claude 4.6 (Opus + Sonnet)', actor: 'Anthropic', accent: 'anthropic', tags: ['anthropic'],
        why: 'Agent teams + native PowerPoint integration.',
        body: 'Opus 4.6 (Feb 5) and Sonnet 4.6 (Feb 17). Added agent-team features and document-creation integrations targeting enterprise workflows.' },
      { date: 'Mar 2026', title: '$122B round, $852B valuation', actor: 'OpenAI', accent: 'funding', tags: ['openai', 'funding'],
        why: 'Approaching trillion-dollar private valuation.',
        body: 'Amazon, Microsoft, and Nvidia anchor. Reflects both OpenAI\'s market position and the obscene capital required to build at the frontier.' },
      { date: 'Apr 2026', title: 'Claude Opus 4.7 + Amazon adds up to $25B', actor: 'Anthropic / Amazon', accent: 'anthropic', tags: ['anthropic', 'funding'],
        why: 'Amazon\'s commitment could reach $33B total.',
        body: 'Opus 4.7 ships with continued reasoning improvements. Amazon announces up to $25B additional infrastructure investment. The Microsoft–OpenAI vs. Amazon–Anthropic rivalry is now structural.' },
      { date: 'Apr 2026', title: 'Musk v. OpenAI trial begins', actor: 'Elon Musk vs. Altman, Brockman', accent: 'drama', tags: ['openai', 'drama'],
        why: 'The 2018 rift finally goes to court.',
        body: 'Trial in Oakland federal court. Musk seeks $134B in damages and removal of Altman/Brockman, alleging OpenAI abandoned its nonprofit mission. Settlement texts surface days before trial.' },
    ]
  },
  {
    id: 'explosion',
    number: 6,
    title: 'The Field Explodes',
    range: '2023 – 2026',
    blurb: 'The race isn\'t two horses — it\'s a stampede.',
    events: [
      { date: 'Feb 2024', title: 'Gemini 1.5 — 1M context', actor: 'Google DeepMind', accent: 'google', tags: ['google'],
        why: 'Google jumps past everyone on context length.',
        body: 'Million-token context window. Could ingest entire codebases, hours of video, or hundreds of documents in a single prompt. Set a new bar competitors are still chasing.' },
      { date: 'Mar 2024', title: 'NVIDIA Blackwell (B100/B200)', actor: 'NVIDIA', accent: 'nvidia', tags: ['nvidia', 'infrastructure'],
        why: '2.5x training performance over H100. The new gold standard.',
        body: 'Announced at GTC 2024. Quickly became the most coveted training hardware on Earth. NVIDIA cemented its role as the "picks and shovels" winner of the AI gold rush.' },
      { date: 'Apr 2024', title: 'LLaMA 3 family', actor: 'Meta', accent: 'meta', tags: ['meta'],
        why: 'Open-source closes the gap on proprietary models.',
        body: '8B, 70B, and 405B parameter variants. The 405B model rivaled GPT-4 quality — fully open. Accelerated open-source AI parity with frontier closed models.' },
      { date: 'Jul 2024', title: 'LLaMA 3.1 with 128K context', actor: 'Meta', accent: 'meta', tags: ['meta'],
        why: '16× context jump for open models.',
        body: 'Set a new ceiling for open-source long-document reasoning. Made Meta\'s open releases competitive with closed models on enterprise use cases.' },
      { date: 'Sep 2024', title: 'Microsoft restarts Three Mile Island', actor: 'Microsoft', accent: 'microsoft', tags: ['microsoft', 'infrastructure'],
        why: 'AI compute now demands nuclear-scale electricity.',
        body: '20-year power purchase agreement with Constellation Energy to restart the shuttered TMI reactor. Powering AI is now a national infrastructure question.' },
      { date: 'Oct 2024', title: 'NVIDIA hits $4T market cap', actor: 'NVIDIA', accent: 'nvidia', tags: ['nvidia', 'funding'],
        why: 'One of the most valuable companies on Earth.',
        body: 'By early 2025, $5T. Reshaped global semiconductor and capital markets entirely on the back of AI demand for GPUs.' },
      { date: 'Dec 2024', title: 'DeepSeek V3', actor: 'DeepSeek (China)', accent: 'deepseek', tags: ['deepseek'],
        why: 'Chinese lab matches GPT-4 at a fraction of the cost.',
        body: 'V3 lands at GPT-4-class quality on key benchmarks. Built efficiently, with significantly less compute. Began the "maybe this isn\'t a moat" conversation in the US.' },
      { date: 'Dec 2024', title: 'Gemini 2.0 — agentic era model', actor: 'Google DeepMind', accent: 'google', tags: ['google'],
        why: 'Google positions for the agentic AI era.',
        body: 'First Gemini explicitly designed for agentic workloads — multi-step tool use, reasoning, planning. Google reorients its strategy.' },
      { date: 'Jan 2025', title: 'DeepSeek R1 shocks markets', actor: 'DeepSeek (China)', accent: 'deepseek', tags: ['deepseek'],
        why: 'Reportedly trained for ~$5.6M and rivals OpenAI\'s o1.',
        body: 'Open-weight reasoning model that rivals o1 on math benchmarks. Reportedly trained at a tiny fraction of US frontier cost. Crashed US tech stocks for a day. Forced US labs to seriously rethink efficiency.' },
      { date: 'Jan 2025', title: 'Stargate Project announced', actor: 'OpenAI / Oracle / SoftBank', accent: 'infrastructure', tags: ['openai', 'infrastructure', 'funding'],
        why: '$500B over 4 years for AI compute infrastructure.',
        body: 'Possibly the largest private infrastructure project in history. First Texas data center opened Sept 2025; multiple US states targeted. Made nation-scale AI infrastructure a real thing.' },
      { date: '2025', title: 'LLaMA 4 — mixture-of-experts', actor: 'Meta', accent: 'meta', tags: ['meta'],
        why: 'Scaling without proportional cost increase.',
        body: 'Adopts mixture-of-experts (MoE) architecture, where only a subset of parameters activate per query. Enables much larger model "size" with manageable runtime cost.' },
      { date: 'May 2025', title: 'Gemini 2.5 + Project Astra', actor: 'Google DeepMind', accent: 'google', tags: ['google'],
        why: 'Google goes hard into video-aware, real-world AI.',
        body: 'Gemini 2.5 with "Deep Think" reasoning mode. Project Astra — a live, video-aware AI assistant. Repositioned Google around embodied, real-world-aware AI.' },
      { date: '2025–26', title: 'Agentic AI ships everywhere', actor: 'All major labs', accent: 'infrastructure', tags: ['openai', 'anthropic', 'infrastructure'],
        why: 'AI moves from "chat" to "do."',
        body: 'OpenAI Agents SDK, Anthropic Claude Agent SDK, AWS Strands all ship. Models browse, write code, control computers, and complete multi-step tasks at scale across enterprise.' },
    ]
  },
];

const VS_TABLE = [
  { date: 'Mar 2023', openai: 'GPT-4', anthropic: 'Claude 1' },
  { date: 'Jul 2023', openai: '—', anthropic: 'Claude 2 (public)' },
  { date: 'Nov 2023', openai: 'GPT-4 Turbo (128K context)', anthropic: 'Claude 2.1 (200K context)' },
  { date: 'Mar 2024', openai: '—', anthropic: 'Claude 3 (Haiku / Sonnet / Opus)' },
  { date: 'May 2024', openai: 'GPT-4o (text+image+audio+video)', anthropic: '—' },
  { date: 'Jun 2024', openai: '—', anthropic: 'Claude 3.5 Sonnet (beats Opus)' },
  { date: 'Sep 2024', openai: 'o1 — first reasoning model', anthropic: '—' },
  { date: 'Oct 2024', openai: '—', anthropic: 'Claude 3.5 Haiku + Computer Use' },
  { date: 'Nov 2024', openai: '—', anthropic: 'MCP open-sourced' },
  { date: 'Dec 2024', openai: 'o3 + Sora public', anthropic: '—' },
  { date: 'Feb 2025', openai: '—', anthropic: 'Claude 3.7 + Claude Code' },
  { date: 'May 2025', openai: '—', anthropic: 'Claude 4 (Sonnet 4, Opus 4)' },
  { date: 'Aug 2025', openai: 'GPT-5', anthropic: '—' },
  { date: 'Sep–Nov 2025', openai: '—', anthropic: 'Claude 4.5 (first to break 80% on SWE-bench)' },
  { date: 'Dec 2025', openai: 'GPT-5.2', anthropic: '—' },
  { date: 'Feb 2026', openai: 'GPT-5.3-Codex', anthropic: 'Claude 4.6 (Opus + Sonnet)' },
  { date: 'Apr 2026', openai: 'GPT-5.5', anthropic: 'Claude Opus 4.7' },
];

const CEOS = [
  {
    name: 'Sam Altman', role: 'CEO, OpenAI', accent: 'openai',
    predictions: [
      { time: '2025', text: 'AI agents "join the workforce."' },
      { time: '2026', text: 'Systems "discover novel insights."' },
      { time: '2027', text: 'Real-world humanoid robots.' },
      { time: '2032–35', text: 'Superintelligence ("a few thousand days").' },
    ]
  },
  {
    name: 'Dario Amodei', role: 'CEO, Anthropic', accent: 'anthropic',
    predictions: [
      { time: 'Oct 2024', text: '"Machines of Loving Grace" essay published.' },
      { time: '2026', text: 'Powerful AI plausibly arrives.' },
      { time: '2030–35', text: '"Compressed 21st century" — 50–100 years of biomedical progress in 5–10.' },
    ]
  },
  {
    name: 'Demis Hassabis', role: 'CEO, Google DeepMind', accent: 'google',
    predictions: [
      { time: '2025', text: 'States AGI is 5–10 years out.' },
      { time: '2030–35', text: 'AGI plausibly arrives.' },
      { time: 'Beyond', text: '"10× the Industrial Revolution, happening 10× faster."' },
    ]
  }
];

const FUTURE_WINDOWS = [
  { range: '2025–26', text: 'Agentic AI in production; reasoning models become standard.', accent: 'openai' },
  { range: '2026–27', text: 'First serious AI scientific discoveries; real coding autonomy.', accent: 'anthropic' },
  { range: '2027–30', text: 'Plausible window for AGI (general human-level AI).', accent: 'research' },
  { range: '2030–35', text: 'Plausible window for superintelligence (AI beyond humans).', accent: 'drama' },
];

const CONSTRAINTS = [
  { name: 'Electricity', body: 'Nuclear restarts, grid buildout. May be the real bottleneck.', accent: 'infra' },
  { name: 'Chip supply', body: 'NVIDIA, TSMC, geopolitics around Taiwan.', accent: 'nvidia' },
  { name: 'Data', body: 'The "data wall" — synthetic data is the bet.', accent: 'research' },
  { name: 'Capital', body: '$100B+ training runs, trillion-dollar infrastructure.', accent: 'funding' },
  { name: 'Regulation', body: 'EU AI Act, US executive orders, China policy.', accent: 'drama' },
];
